#!/bin/bash
echo -e '\e[32mHook post-commit started.\e[0m'
echo '#################################################################################'
echo '#                                                                               #'
echo '# To deploy commits for a branch to a local or mapped directory, add a local    #'
echo '# config item:                                                                  #'
echo '#                                                                               #'
echo '#    git config --local deploy.branch "branch_name /path/to/deploy"             #'
echo '#                                                                               #'
echo '# To deploy additional branches, add more mappings to the local config:         #'
echo '#                                                                               #'
echo '#    git config --local --add "branch2 /path/to/deploy2"                        #'
echo '#                                                                               #'
echo '# To deploy the same branch to multiple directories, add more mappings to the   #'
echo '# local config specifying the same branch again:                                #'
echo '#                                                                               #'
echo '#    git config --local --add "branch2 /second/path/to/deploy2"                 #'
echo '#                                                                               #'
echo '# To clean the deployment directory before deploying the commit, add a config   #'
echo '# item (note that this option applies to all deployment mappings and will not   #'
echo '# clean subdirectories that are not part of the commit):                        #'
echo '#                                                                               #'
echo '#    git config deploy.clean true                                               #'
echo '#                                                                               #'
echo '#################################################################################'

unset GIT_INDEX_FILE
export GIT_DIR=./.git

this_branch=$( git branch | grep '^\*\s[^\s]' | cut -c 3- )
is_deployed=false

while read -r line; do
	read -r branch dir <<< $line

	if [ "$this_branch" == "$branch" ]; then
		echo -e "\e[32mDeploying branch $this_branch to $dir.\e[0m"
		
		if [ $( git config deploy.clean ) == true ]; then
			echo -e "\e[32mCleaning $dir.\e[0m"
			
			git --work-tree $dir clean -f
		fi

		git --work-tree $dir checkout -f
		is_deployed=true
	fi
done < <( git config --get-all deploy.branch ) 

if [ $is_deployed == false ]; then
	echo -e "\e[33mDid not deploy branch $this_branch.\e[0m"
fi

echo -e '\e[32mHook post-commit finished.\e[0m'
